const exampleArtistDetails = {
	success: true,
	data: {
		id: "1274170",
		name: "Dua Lipa",
		url: "https://www.jiosaavn.com/artist/dua-lipa/r-OWIKgpX2I_",
		type: "artist",
		followerCount: 729744,
		fanCount: "430980",
		isVerified: true,
		dominantLanguage: "english",
		dominantType: "music director",
		bio: [],
		dob: null,
		fb: null,
		twitter: null,
		wiki: null,
		availableLanguages: [
			"english",
			"unknown",
			"instrumental",
			"spanish",
			"french",
			"portuguese",
			"croatian",
			"dutch",
			"hebrew",
			"korean",
		],
		isRadioPresent: true,
		image: [
			{
				quality: "50x50",
				url: "https://c.saavncdn.com/artists/Dua_Lipa_004_20231120090922_50x50.jpg",
			},
			{
				quality: "150x150",
				url: "https://c.saavncdn.com/artists/Dua_Lipa_004_20231120090922_150x150.jpg",
			},
			{
				quality: "500x500",
				url: "https://c.saavncdn.com/artists/Dua_Lipa_004_20231120090922_500x500.jpg",
			},
		],
		topSongs: [],
		topAlbums: [],
		singles: [],
		similarArtists: [],
	},
};
export default exampleArtistDetails;
